### ISSUE TITLE
Unknown block type "cloudinary.asset", please specify a serializer for it in the `serializers.types` prop

### ISSUE THREAD

**Issue by ajmalafif** [sanity-io/sanity-plugin-cloudinary#8]
hey 👋🏽 

So I think I am very close here, I managed to make Cloudinary appear on Sanity, but on frontend (gatsby), I am getting this error:

```
Unknown block type "cloudinary.asset", please specify a serializer for it in the `serializers.types` prop
```

![CleanShot 2021-11-17 at 21 48 29@2x](https://user-images.githubusercontent.com/827167/142214075-419c33ad-e8a2-49c7-a0b4-10ceb8736c56.jpg)
![CleanShot 2021-11-17 at 21 49 10@2x](https://user-images.githubusercontent.com/827167/142214086-8152a15a-3f97-4aab-bba5-7528efe459b1.jpg)

What does it means?

**Comment by marcos-abreu** [comment]
I don't have a lot of experience with this plugin (just built my first site using sanity as a cms). But from my experience the issue you found is related with use of `block type` (https://www.sanity.io/docs/block-type) without informing a proper serializer for it.

The `@sanity/block-content-to-react` package has the default serializers for a block type. But even this package doesn't include the serializer for `cloudinary` images/videos.

So basically you are able to create the content on Sanity and you should even be able to see that on the gatsby graphql development server. But when Gatsby try to convert the content from your block type it doesn't know how to translate that to react components.

If you are already using the  `@sanity/block-content-to-react` you probably are only missing a serializer for cloudinary image/videos, and you will have to build one. Unfortunately I haven't create one myself since I didn't need to include cloudinary on a `block type`. Here is a link for some serializers created for a block type for your reference:

https://github.com/sanity-io/block-content-to-hyperscript/blob/main/src/serializers.js
